version: '2.3'
services:
  mqtt:
    image: eclipse-mosquitto
    volumes:
      - ./mqtt/config/:/mosquitto/config/
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    ports:
      # WARNING:
      # ONLY USE PORT 1883 internally !! --> No TLS
      # Use port 8883 from outside (encrypted w/ TLS)
      #
      # Let's try WITHOUT (todo: remove if working (also remove in mosquitto config))
      # - 1883:1883
      - $MQTT_PORT:8883
    restart: always

  webhooks:
    build: ./webhooks
    ports:
      - $WEBHOOKS_PORT:5000
    environment:
      - "FLASK_APP=webhooks.py"
    restart: always
