version: '2.3'
services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./config/:/mosquitto/config/
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    ports:
      # WARNING:
      # ONLY USE PORT 1883 internally !! --> No TLS
      # Use port 8883 from outside (encrypted w/ TLS)
      #
      # Let's try WITHOUT (todo: remove if working (also remove in mosquitto config))
      # - 1883:1883
      - $MQTT_PORT:8883
    restart: always
